#!/usr/bin/env bash
#
# Yoyo Collection — one-line installer.
#
#     curl -fsSL https://raw.githubusercontent.com/stammig/yoyo-collection/main/install.sh | bash
#
# Creates a folder (~/yoyo-collection by default), pulls the prebuilt Docker
# image from GHCR, and starts the app on http://localhost:3000. Re-run it any
# time to update to the latest version — your data is untouched.
#
# Optional environment overrides:
#   YOYO_DIR=/opt/yoyo     install location            (default: ~/yoyo-collection)
#   YOYO_PORT=8080         host port to serve on       (default: 3000)
#   YOYO_IMAGE=...:v1.2.3  pin a specific image tag    (default: ...:latest)
#   ADMIN_PASSWORD=secret  set the owner password non-interactively
#
set -euo pipefail

IMAGE="${YOYO_IMAGE:-ghcr.io/stammig/yoyo-collection:latest}"
DIR="${YOYO_DIR:-$HOME/yoyo-collection}"
PORT="${YOYO_PORT:-3000}"

# ---- pretty output -------------------------------------------------------
if [ -t 1 ]; then
  BOLD=$'\033[1m'; DIM=$'\033[2m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; RESET=$'\033[0m'
else
  BOLD=""; DIM=""; GREEN=""; YELLOW=""; RED=""; RESET=""
fi
say()  { printf '%s\n' "$*"; }
step() { printf '%s▸%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '%s! %s%s\n' "$YELLOW" "$*" "$RESET"; }
die()  { printf '%s✗ %s%s\n' "$RED" "$*" "$RESET" >&2; exit 1; }

printf '\n%s🪀  Yoyo Collection installer%s\n\n' "$BOLD" "$RESET"

# ---- preflight: Docker ---------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  die "Docker isn't installed. Install Docker Desktop (Mac/Windows) or Docker Engine (Linux):
     https://docs.docker.com/get-docker/
   then re-run this installer."
fi

# Compose v2 is a docker subcommand ("docker compose"); the old standalone
# "docker-compose" v1 is not supported here.
if ! docker compose version >/dev/null 2>&1; then
  die "Docker Compose v2 isn't available. Update Docker Desktop, or install the
   compose plugin: https://docs.docker.com/compose/install/"
fi

if ! docker info >/dev/null 2>&1; then
  die "Docker is installed but the daemon isn't running. Start Docker Desktop
   (or 'sudo systemctl start docker' on Linux) and re-run this installer."
fi

# ---- create install dir --------------------------------------------------
COMPOSE_FILE="$DIR/docker-compose.yml"
UPDATING=0
if [ -f "$COMPOSE_FILE" ]; then UPDATING=1; fi

step "Install folder: $DIR"
mkdir -p "$DIR"

# ---- owner password (fresh installs only) --------------------------------
# When run through "curl | bash", stdin is the script itself, so prompts must
# read from the terminal directly (/dev/tty). If there's no terminal and no
# ADMIN_PASSWORD was provided, we install in fully-open mode and say so.
if [ "$UPDATING" -eq 0 ]; then
  # Only prompt if the controlling terminal actually opens (fd 3). Guarding on
  # "[ -r /dev/tty ]" isn't enough — the device can exist yet be unusable in CI
  # or detached shells, which would leak an error. Opening it here fails cleanly.
  if [ -z "${ADMIN_PASSWORD:-}" ] && { exec 3</dev/tty; } 2>/dev/null; then
    say ""
    say "Set an ${BOLD}owner password${RESET} so the public view is read-only and you log in to edit."
    say "${DIM}Leave it blank to run fully open — anyone who reaches the app can edit.${RESET}"
    printf 'Owner password (hidden, optional): '
    # -s hides typing; tolerate EOF/interrupt without aborting the install.
    ADMIN_PASSWORD=""
    read -rs ADMIN_PASSWORD <&3 || ADMIN_PASSWORD=""
    exec 3<&-
    printf '\n'
  fi
  : "${ADMIN_PASSWORD:=}"

  # Write the compose file (pulls the prebuilt image).
  step "Writing docker-compose.yml"
  cat > "$COMPOSE_FILE" <<YAML
# Generated by install.sh — Yoyo Collection.
# Update:  docker compose pull && docker compose up -d
# Stop:    docker compose down          (your data stays in the yoyo-data volume)
services:
  yoyo:
    image: ${IMAGE}
    ports:
      - "${PORT}:3000"
    volumes:
      - yoyo-data:/data
    # Owner login lives in the .env file next to this one. env_file passes the
    # value to the container verbatim — no YAML escaping, no \$-interpolation —
    # so any password (spaces, \$, #, quotes) is safe.
    env_file:
      - .env
    environment:
      DB_PATH: /data/yoyos.db
      UPLOAD_DIR: /data/uploads
    restart: unless-stopped

volumes:
  yoyo-data:
YAML

  # Keep the password out of the YAML entirely. An empty value = login disabled
  # = fully open (the app treats an empty ADMIN_PASSWORD as unset).
  umask 077
  printf 'ADMIN_PASSWORD=%s\n' "$ADMIN_PASSWORD" > "$DIR/.env"
  umask 022
  if [ -n "$ADMIN_PASSWORD" ]; then
    say "  ${DIM}Owner password saved to $DIR/.env${RESET}"
  else
    warn "Running in fully-open mode (no owner password set)."
    say "  ${DIM}To lock editing later: edit ADMIN_PASSWORD in $DIR/.env, then${RESET}"
    say "  ${DIM}cd $DIR && docker compose up -d${RESET}"
  fi
fi

# ---- pull + start --------------------------------------------------------
cd "$DIR"
step "Pulling the latest image ($IMAGE)"
docker compose pull

step "Starting Yoyo Collection"
docker compose up -d

# ---- done ----------------------------------------------------------------
URL="http://localhost:${PORT}"
say ""
if [ "$UPDATING" -eq 1 ]; then
  printf '%s✓ Updated and restarted.%s  %s\n' "$GREEN$BOLD" "$RESET" "$URL"
else
  printf '%s✓ Yoyo Collection is running!%s\n\n' "$GREEN$BOLD" "$RESET"
  say "   Open:    ${BOLD}${URL}${RESET}"
  say "   Folder:  ${DIR}"
fi
say ""
say "${DIM}Manage it (run from ${DIR}):${RESET}"
say "   docker compose logs -f            # watch the logs"
say "   docker compose pull && docker compose up -d   # update"
say "   docker compose down               # stop (data is kept)"
say ""
say "${DIM}Back up everything from inside the app: Settings ⚙ → Backup (one .zip).${RESET}"
say ""
